### ISSUE TITLE
Roadmap to 1.0.1

### ISSUE THREAD

**Issue by DartPower** [dpteam/GLQuake3D#10]
Before releasing from 1.0.0 to 1.0.1 need to release this features.
- [ ] Find a coder...
- [ ] Complete this #9 
- [ ] Made automatic adoon support and scanning. (dopa & etc)
- [ ] Fix network code for play it online with friends (and not only) in internet & lan.
- [ ] Simple configurator UI (Playername, launch parameters & etc)
- [ ] New blue fog enabling only on known & need maps.
- [ ] Made loading bar
- [ ] Improve shadows code
- [ ] Add the windows userstyles support
- [ ] Fix the weapon interpolating

Known bugs:
 - Current working only "GL Release" & "GL Debug" (WinQuake's Debug & Release currently not working.)
 - Not available Linux makefiles
 - Render still glitches sometimes (to reproduce this bug, use the this command: gl_flashblend 1)
 - Fog incorrectly rendering the glowing and flash-blending
